version: '3'

services:
  user_management:
    image: akshaymisra24/go-cart-user-management:0.1.0
    ports:
      - "4000:4000"
  product_management:
    image: akshaymisra24/go-cart-product-management:0.1.0
    ports:
      - "4100:4100"

#  hazelcast:
#    image: hazelcast/hazelcast:5.3.2
#    ports:
#      - "5701:5701"
#
#  management-center:
#    image: hazelcast/management-center:5.0
#    environment:
#      - MC_CLUSTER_MEMBERS=hzl
#    ports:
#      - "8080:8080"
#    depends_on:
#      - hazelcast
